// client/src/CheckoutForm.js
// Component for handling Stripe payment during order checkout
// Includes contact info fields for phone and email

import React, { useState, useEffect } from 'react';
import { PaymentElement, useStripe, useElements } from '@stripe/react-stripe-js';
import './NewOrder.css';

export default function CheckoutForm({ onPaymentSuccess, onCancel, initialContact = {} }) {
  // Stripe hooks
  const stripe = useStripe();
  const elements = useElements();
  const [message, setMessage] = useState(null);
  const [isProcessing, setIsProcessing] = useState(false);
  const [phone, setPhone] = useState('');
  const [email, setEmail] = useState('');

  // Pre-fill contact info if provided
  useEffect(() => {
    if (initialContact) {
      if (initialContact.phone) setPhone(initialContact.phone);
      if (initialContact.email) setEmail(initialContact.email);
    }
  }, [initialContact]);

  // Handle form submission
  const handleSubmit = async (e) => {
    e.preventDefault();

    if (!stripe || !elements) {
      return;
    }

    setIsProcessing(true);

    // Confirm the payment with Stripe
    const { error, paymentIntent } = await stripe.confirmPayment({
      elements,
      confirmParams: {
        return_url: window.location.origin + "/order-history",
      },
      redirect: "if_required",
    });

    // Handle payment result
    if (error) {
      setMessage(error.message);
      setIsProcessing(false);
    } else if (paymentIntent && paymentIntent.status === "succeeded") {
      // Payment succeeded! Now place the order in our DB and include contact info
      onPaymentSuccess(paymentIntent.id, { phone, email });
    } else {
      setMessage("Unexpected state.");
      setIsProcessing(false);
    }
  };

  // Outline of the following frontend components generated by AI:
  // Render payment form with contact info fields
  return (
    <form onSubmit={handleSubmit} className="payment-form-box">
      <h4>Contact Info</h4>
      <div className="form-group">
        <label htmlFor="cf_phone">Phone Number</label>
        <input
          id="cf_phone"
          type="text"
          inputMode="tel"
          value={phone}
          onChange={(e) => setPhone(e.target.value.replace(/[^0-9+()-\s]/g, ''))}
          placeholder="e.g., 6095551234"
        />
      </div>
      <div className="form-group">
        <label htmlFor="cf_email">Email</label>
        <input
          id="cf_email"
          type="email"
          value={email}
          onChange={(e) => setEmail(e.target.value)}
          placeholder="you@example.com"
        />
      </div>
      <h3>Enter Card Details</h3>
      <PaymentElement />
      {message && <div className="error-message" style={{marginTop: '10px'}}>{message}</div>}
      
      <div className="form-actions" style={{justifyContent: 'flex-end', marginTop: '20px'}}>
        <button 
            type="button" 
            className="action-button-secondary" 
            onClick={onCancel} 
            disabled={isProcessing}
            style={{marginRight: '10px'}}
        >
          Cancel
        </button>
        <button 
            type="submit" 
            className="save-button" 
            disabled={isProcessing || !stripe || !elements}
        >
          {isProcessing ? "Processing..." : "Pay Now"}
        </button>
      </div>
    </form>
  );
}