// client/src/DashboardLanding.js
// Component that redirects users to their appropriate dashboard based on role

import React, { useEffect } from 'react';
import { useNavigate } from 'react-router-dom';

function DashboardLanding() {
  const navigate = useNavigate();

  useEffect(() => {
    // Fetch the user's profile to get their role
    fetch('/profile')
      .then(res => {
        if (!res.ok) {
          // If not authenticated, send to home page
          throw new Error('Not authenticated');
        }
        return res.json();
      })
      .then(user => {
        // Redirect based on user role
        if (user.role === 'admin') {
          navigate('/admin');
        } else if (user.role === 'driver') {
          navigate('/driver-dashboard'); 
        } else {
          // Default to student dashboard
          navigate('/student-dashboard');
        }
      })
      // If error (e.g., not authenticated), redirect to home
      .catch(error => {
        console.error("Error fetching profile:", error);
        navigate('/'); 
      });
  }, [navigate]);

  // Outline of the following frontend components generated by AI:
  // Display a loading state while we figure out where to go
  return (
    <div style={{ padding: '50px', textAlign: 'center', fontFamily: 'Helvetica, Arial, sans-serif', fontSize: '1.5em' }}>
      Loading your dashboard...
    </div>
  );
}

export default DashboardLanding;