// client/src/Header.js
// Reusable header component with dynamic navigation links and login/logout button

import React, { useState, useEffect } from 'react';
import { Link } from 'react-router-dom';
import './Header.css';

function Header({ hideLogin = false }) {
  const [user, setUser] = useState(null);
  const [navOpen, setNavOpen] = useState(false);

  // Fetch user profile on component mount to determine login status and role
  useEffect(() => {
    fetch('/profile')
      .then(res => {
        if (res.ok) {
          return res.json();
        }
        return null;
      })
      .then(userData => {
        if (userData) {
          setUser(userData);
        }
      })
      .catch(error => console.error("Error fetching profile:", error));
  }, []);

  // Outline of the following frontend components generated by AI:
  // Render header with dynamic links and login/logout button
  return (
    <header className={`app-header ${navOpen ? 'nav-open' : ''}`}>
      <div className="header-left-side">
        <div className="logo-container">
          <Link to="/student-dashboard" className="logo-link">
            <span role="img" aria-label="utensils" style={{ marginRight: '8px' }}>🍴</span>
            UniEats
          </Link>
        </div>
        {/* Show mobile menu toggle only for driver/admin users (desktop hides it via CSS) */}
        {user && (user.role === 'driver' || user.role === 'admin') && (
          <button
            className="menu-toggle"
            aria-label="Toggle navigation"
            onClick={() => setNavOpen(open => !open)}
          >
            <span className="hamburger" />
          </button>
        )}

        <nav className="header-nav">
          {user && (user.role === 'driver' || user.role === 'admin') && (
            <Link to="/student-dashboard" className="header-nav-link">Student Dashboard</Link>
          )}
          {user && (user.role === 'driver' || user.role === 'admin') && (
            <Link to="/driver-dashboard" className="header-nav-link">Driver Dashboard</Link>
          )}
          {user && user.role === 'admin' && (
            <Link to="/admin" className="header-nav-link">Admin Center</Link>
          )}
        </nav>
      </div>

      {!hideLogin && (
        <div className="user-profile">
          {user ? (
            <>
              <span className="user-name">Welcome, {user.name}!</span>
              <a href="/logout" className="logout-button-link">
                <button className="logout-button">Logout</button>
              </a>
            </>
          ) : (
            <a href="/login" className="logout-button-link">
              <button className="logout-button">Login</button>
            </a>
          )}
        </div>
      )}
      {/* Mobile overlay nav (covers screen when open). Rendered for drivers/admin only. */}
      {navOpen && user && (user.role === 'driver' || user.role === 'admin') && (
        <div className="mobile-nav-overlay" onClick={() => setNavOpen(false)}>
          <nav className="mobile-nav" onClick={(e) => e.stopPropagation()}>
            {user && (user.role === 'driver' || user.role === 'admin') && (
              <Link to="/student-dashboard" className="mobile-nav-link" onClick={() => setNavOpen(false)}>Student Dashboard</Link>
            )}
            {user && (user.role === 'driver' || user.role === 'admin') && (
              <Link to="/driver-dashboard" className="mobile-nav-link" onClick={() => setNavOpen(false)}>Driver Dashboard</Link>
            )}
            {user && user.role === 'admin' && (
              <Link to="/admin" className="mobile-nav-link" onClick={() => setNavOpen(false)}>Admin Center</Link>
            )}
          </nav>
        </div>
      )}
    </header>
  );
}

export default Header;