// client/src/Settings.js
// Component for user profile and settings with dynamic back navigation

import React, { useState, useEffect } from 'react';
import { Link, useNavigate, useLocation } from 'react-router-dom'; 
import './Settings.css';
import Header from './Header';

function Settings() {
  // State variables for form data and loading status
  const [formData, setFormData] = useState({
    name: '',
    email: '',
    phone_number: '',
    notify_email_order_status: true,
    notify_email_promotions: true,
  });
  const [statusMessage, setStatusMessage] = useState('');
  const [isLoading, setIsLoading] = useState(true);
  const navigate = useNavigate();
  const location = useLocation();

  // Determine back URL dynamically
  const backUrl = location.state?.from || '/student-dashboard';

  // Fetch user profile on component mount
  useEffect(() => {
    fetch('/profile')
      .then(res => {
        if (!res.ok) throw new Error('Not authenticated');
        return res.json();
      })
      .then(user => {
        setFormData({
          name: user.name || '',
          email: user.email || '', 
          phone_number: user.phone_number || '',
          notify_email_order_status: user.notify_email_order_status,
          notify_email_promotions: user.notify_email_promotions
        });
      })
      .catch(error => {
        console.error("Error fetching profile:", error);
        navigate('/');
      })
      .finally(() => setIsLoading(false));

  }, [navigate]);

  // Handle form input changes
  const handleChange = (e) => {
    const { name, value, type, checked } = e.target;
    const newValue = type === 'checkbox' ? checked : value;
    setFormData(prevData => ({
      ...prevData,
      [name]: newValue,
    }));
  };

  // Handle form submission to save settings
  const handleSubmit = (e) => {
    e.preventDefault();
    setStatusMessage('Saving...');
    const payload = { ...formData };
    fetch('/profile', {
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(payload),
    })
    .then(res => res.json())
    .then(data => {
      if (data.error) throw new Error(data.error);
      setStatusMessage('Settings saved successfully!');
      setFormData(prevData => ({ ...prevData, ...data }));
    })
    .catch(err => {
      console.error('Error saving settings:', err);
      setStatusMessage('Error saving settings. Please try again.');
    });
  };
  
  // Render loading state
  if (isLoading) {
    return (
      <div className="page-container settings-page">
        <Header />
        <main className="page-main">Loading...</main>
      </div>
    );
  }
  
  // Outline of the following frontend components generated by AI:
  // Render settings form
  return (
    <div className="page-container settings-page">
      <Header />
      <main className="page-main">
        <header className="settings-header">
          <h1>Profile & Settings</h1>
          {/* 4. Use the dynamic backUrl */}
          <Link to={backUrl} className="back-link">&larr; Back</Link>
        </header>

        <form onSubmit={handleSubmit} className="settings-form">
        <section className="settings-section">
          <h2>Profile</h2>
          <div className="form-group">
            <label htmlFor="name">Full Name</label>
            <input
              type="text"
              id="name"
              name="name"
              value={formData.name}
              onChange={handleChange}
            />
          </div>
          <div className="form-group">
            <label htmlFor="email">Email (read-only)</label>
            <input
              type="email"
              id="email"
              name="email"
              value={formData.email}
              readOnly
              disabled
            />
          </div>
          <div className="form-group">
            <label htmlFor="phone_number">Phone Number</label>
            <input
              type="tel"
              id="phone_number"
              name="phone_number"
              value={formData.phone_number}
              onChange={handleChange}
              placeholder="e.g., 555-123-4567"
            />
          </div>
        </section>
        
        <section className="settings-section">
          <h2>Email Notifications</h2>
          <div className="form-group-checkbox">
            <input
              type="checkbox"
              id="notify_email_order_status"
              name="notify_email_order_status"
              checked={formData.notify_email_order_status}
              onChange={handleChange}
            />
            <label htmlFor="notify_email_order_status">Order Status Updates</label>
          </div>
          <div className="form-group-checkbox">
            <input
              type="checkbox"
              id="notify_email_promotions"
              name="notify_email_promotions"
              checked={formData.notify_email_promotions}
              onChange={handleChange}
            />
            <label htmlFor="notify_email_promotions">Promotions & News</label>
          </div>
        </section>
        
        <div className="form-actions">
          <button type="submit" className="save-button">Save Settings</button>
          {statusMessage && <span className="status-message">{statusMessage}</span>}
        </div>
        </form>
      </main>
    </div>
  );
}

export default Settings;