// client/src/StudentDashboard.js
// Student dashboard showing current order status, recent orders, and quick actions
// with real-time updates via WebSocket and responsive design for order tracker

import React, { useState, useEffect } from 'react';
import { Link } from 'react-router-dom';
import Header from './Header'; 
import './Dashboard.css'; 
import { formatStatus, statusClass } from './utils/statusUtils';
import { formatPhoneForDisplay, formatPhoneForTel } from './utils/phoneUtils';
import socket, { register } from './utils/socket';

function StudentDashboard() {
  // State variables
  const [recentOrders, setRecentOrders] = useState([]); 
  const [activeOrder, setActiveOrder] = useState(null);
  const [isLoading, setIsLoading] = useState(true); 
  const [graceSeconds, setGraceSeconds] = useState(300); 
  const [remainingSeconds, setRemainingSeconds] = useState(null);

  // Format ISO date string to readable format
  const formatTime = (isoString) => {
    return new Date(isoString).toLocaleString('en-US', {
      month: 'short',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit'
    });
  };

  // Fetch dashboard data on component mount
  useEffect(() => {
    // Fetch order history and also register socket for real-time updates
    fetch('/api/orders/my-history')
      .then(res => {
        if (!res.ok) throw new Error('Failed to fetch order history');
        return res.json();
      })
      .then(orderData => {
        setRecentOrders(orderData.slice(0, 3)); 
        // Determine active order
        // Find the most recent order that is not delivered or cancelled
        // If none, check for recently delivered within grace period
        // If still none, activeOrder remains null
        const sorted = orderData.slice().sort((a,b) => new Date(b.created_at) - new Date(a.created_at));
        let active = sorted.find(o => {
          const s = (o.status || 'pending');
          return s !== 'delivered' && s !== 'cancelled';
        });
        if (!active) {
          const recentlyDelivered = sorted.find(o => {
            const s = (o.status || 'pending');
            if (s !== 'delivered') return false;
            const deliveredAt = o.updated_at || o.delivered_at || o.created_at;
            if (!deliveredAt) return false;
            const diff = Date.now() - new Date(deliveredAt).getTime();
            return diff <= (graceSeconds * 1000);
          });
          active = recentlyDelivered || null;
        }
        setActiveOrder(active || null);
        // Register socket for real-time updates
        fetch('/profile').then(r => r.ok ? r.json() : null).then(user => {
          if (user) register({ userId: user.id, role: user.role });
        }).catch(e => console.warn('Failed to register socket for student', e));
      })
      .catch(error => console.error("Error fetching dashboard data:", error))
      .finally(() => setIsLoading(false));
  }, []); 

  // Handle real-time order updates via WebSocket
  useEffect(() => {
    const onOrderUpdated = (order) => {
      // Update the recent orders list
      setRecentOrders(prev => {
        const exists = prev.find(p => p.id === order.id);
        if (exists) {
          return prev.map(p => p.id === order.id ? order : p);
        }
        return [order, ...prev].slice(0,3);
      });
      // Update active order if it matches
      setActiveOrder(prev => {
        if (!prev) {
          if (order.status !== 'delivered' && order.status !== 'cancelled') return order;
          return prev;
        }
        if (prev.id === order.id) return order;
        return prev;
      });
    };

    // Register event listener
    socket.on('order_updated', onOrderUpdated);
    return () => {
      socket.off('order_updated', onOrderUpdated);
    };
  }, []);

  // Render status with appropriate styling
  const renderStatus = (status) => {
    const cls = statusClass(status);
    return <span className={`status-tag status-${cls}`}>{formatStatus(status)}</span>;
  };

  // Steps for order tracker
  const steps = [
    { key: 'pending', label: 'Pending' },
    { key: 'claimed', label: 'Claimed' },
    { key: 'picked_up', label: 'Picked Up' },
    { key: 'en_route', label: 'En Route' },
    { key: 'delivered', label: 'Delivered' },
  ];

  // Responsive design: detect small screens
  const [isSmallScreen, setIsSmallScreen] = useState(typeof window !== 'undefined' ? window.innerWidth <= 600 : false);

  // Update isSmallScreen on window resize
  useEffect(() => {
    const onResize = () => setIsSmallScreen(window.innerWidth <= 600);
    window.addEventListener('resize', onResize);
    return () => window.removeEventListener('resize', onResize);
  }, []);

  // Outline of the following frontend components generated by AI:
  // Render order tracker
  const renderTracker = (order) => {
    if (!order) return null;
    const cur = (order.status || 'pending');
    const curIndex = steps.findIndex(s => s.key === cur);
    let deliveredAgo = null;
    if (cur === 'delivered') {
      const deliveredAt = order.updated_at || order.delivered_at || order.created_at;
      if (deliveredAt) deliveredAgo = Math.floor((Date.now() - new Date(deliveredAt).getTime()) / 1000);
    }

    // Determine visible steps based on screen size
    const visibleSteps = isSmallScreen
      ? steps.slice(Math.max(0, curIndex), Math.min(steps.length, curIndex + 2))
      : steps;

    // Driver info block
    const driverInfo = (order.driver_name || order.driver_phone) ? (
      <div className="tracker-driver">
        <div className="driver-avatar">{(order.driver_name || 'D').split(' ').map(n=>n[0]).slice(0,2).join('')}</div>
        <div className="driver-details">
          <div className="driver-name">Driver: {order.driver_name || 'Assigned'}</div>
          {order.driver_phone ? (
            <a className="driver-phone" href={formatPhoneForTel(order.driver_phone)}>{formatPhoneForDisplay(order.driver_phone)}</a>
          ) : (
            <div className="driver-phone muted">Contact not available</div>
          )}
        </div>
      </div>
    ) : null;

    // If small screen, render tracker first and then the driver info below as its own block
    if (isSmallScreen) {
      return (
        <>
          <div className="order-tracker circle-tracker" aria-hidden={false}>
            {visibleSteps.map((s, i) => {
              const realIdx = steps.findIndex(x => x.key === s.key);
              const state = realIdx < curIndex ? 'done' : (realIdx === curIndex ? 'active' : 'pending');
              return (
                <React.Fragment key={s.key}>
                  <div className={`circle-step ${state}`}>
                    <div className={`circle ${state}`} aria-hidden>
                      {state === 'done' ? '✓' : (realIdx + 1)}
                    </div>
                    <div className="step-label">{s.label}</div>
                  </div>
                  {i < visibleSteps.length - 1 && (
                    <div className={`tracker-arrow ${realIdx < curIndex ? 'done' : ''}`} aria-hidden>
                      <svg className="chev" width="28" height="28" viewBox="0 0 24 24" aria-hidden="true" focusable="false">
                        <path d="M8 5l8 7-8 7" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" />
                      </svg>
                    </div>
                  )}
                </React.Fragment>
              );
            })}

            {cur === 'delivered' && deliveredAgo !== null && (
              <div className="tracker-footer">Delivered — this will move to your order history in {formatRemaining(Math.max(0, graceSeconds - deliveredAgo))}</div>
            )}
          </div>

          {driverInfo}
        </>
      );
    }

    return (
      <div className="order-tracker circle-tracker" aria-hidden={false}>
        {visibleSteps.map((s, i) => {
          const realIdx = steps.findIndex(x => x.key === s.key);
          const state = realIdx < curIndex ? 'done' : (realIdx === curIndex ? 'active' : 'pending');
          return (
            <React.Fragment key={s.key}>
              <div className={`circle-step ${state}`}>
                <div className={`circle ${state}`} aria-hidden>
                  {state === 'done' ? '✓' : (realIdx + 1)}
                </div>
                <div className="step-label">{s.label}</div>
              </div>
              {i < visibleSteps.length - 1 && (
                <div className={`tracker-arrow ${realIdx < curIndex ? 'done' : ''}`} aria-hidden>
                  <svg className="chev" width="28" height="28" viewBox="0 0 24 24" aria-hidden="true" focusable="false">
                    <path d="M8 5l8 7-8 7" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" />
                  </svg>
                </div>
              )}
            </React.Fragment>
          );
        })}

        {driverInfo}

        {cur === 'delivered' && deliveredAgo !== null && (
          <div className="tracker-footer">Delivered — this will move to your order history in {formatRemaining(Math.max(0, graceSeconds - deliveredAgo))}</div>
        )}
      </div>
    );
  };

  // Format remaining seconds as M:SS
  const formatRemaining = (secs) => {
    const m = Math.floor(secs / 60);
    const s = secs % 60;
    return `${m}:${String(s).padStart(2, '0')}`;
  };

  // Countdown for recently delivered orders
  useEffect(() => {
    if (!activeOrder) {
      setRemainingSeconds(null);
      return;
    }
    if ((activeOrder.status || 'pending') !== 'delivered') {
      setRemainingSeconds(null);
      return;
    }
    const deliveredAt = activeOrder.updated_at || activeOrder.delivered_at || activeOrder.created_at;
    if (!deliveredAt) return;
    const updateRemaining = () => {
      const elapsed = Math.floor((Date.now() - new Date(deliveredAt).getTime()) / 1000);
      const rem = Math.max(0, graceSeconds - elapsed);
      setRemainingSeconds(rem);
      if (rem <= 0) {
        setActiveOrder(null);
      }
    };
    updateRemaining();
    const id = setInterval(updateRemaining, 1000);
    return () => clearInterval(id);
  }, [activeOrder, graceSeconds]);

  // Outline of the following frontend components generated by AI:
  // Render main dashboard
  return (
    <div className="page-container">
      <Header />
      <main className="page-main">
        {activeOrder && (
          <section className="dashboard-section">
            <h2>Current Order Status</h2>
            {renderTracker(activeOrder)}
          </section>
        )}
        <h1 className="dashboard-title">Student Dashboard</h1>

        <section className="dashboard-section">
          <h2>Quick Actions</h2>
          <div className="action-buttons">
          
            <Link to="/new-order" className="action-button-link" state={{ from: '/student-dashboard' }}>
              <button className="action-button">Order Food Now!</button>
            </Link>

            <Link to="/order-history" className="action-button-link" state={{ from: '/student-dashboard' }}>
              <button className="action-button">View Order History</button>
            </Link>
            
            <Link to="/settings" className="action-button-link" state={{ from: '/student-dashboard' }}>
              <button className="action-button">
                Profile & Settings
              </button>
            </Link>
            
          </div>
        </section>

        <section className="dashboard-section">
          <h2>Recent Orders</h2>
          {isLoading ? (
            <p>Loading recent orders...</p>
          ) : recentOrders.length === 0 ? (
            <p>You have not placed any orders yet.</p>
          ) : (
            <div className="recent-orders-list">
              {recentOrders.map(order => (
                <div key={order.id} className="recent-order-item">
                  <div className="order-info">
                    <strong>{order.delivery_building}, {order.delivery_room}</strong>
                    <span className="order-time">{formatTime(order.created_at)}</span>
                  </div>
                  {renderStatus(order.status)}
                </div>
              ))}
            </div>
          )}
        </section>
      </main>

      <footer className="page-footer">
        UniEats &copy; 2025
      </footer>
    </div>
  );
}

export default StudentDashboard;